### ISSUE TITLE
Cannot install locally

### ISSUE THREAD

**Issue by VZcoding** [AlturosDestinations/Alturos.ImageAnnotation#19]
Hi, I am getting this error when trying to use your script, why is that?

![1](https://user-images.githubusercontent.com/35932738/65304196-bded6e00-db88-11e9-9e68-5a2075bd35c9.png)

**Comment by tinohager** [comment]
The Path is wrong of your file i think it is not c:\windows\system32

**Comment by VZcoding** [comment]
Thank you!

**Comment by LKneringer** [comment]
You can also run the script by right clicking the file and choosing "Run with PowerShell" from the context menu. We will add this to the documentation.
