### ISSUE TITLE
Errors, bugs

### ISSUE THREAD

**Issue by VZcoding** [AlturosDestinations/Alturos.ImageAnnotation#20]
Actually I dont get it how to even assign labels to the image.. At first application compiled and opened, I was able to add some tags to the list, but could not assign it to image, then i tried to add some objects because the only label on the image I could see was default "MyObject" after doing so application does not compile anymore... throwing this exception, could you please add more detailed information how to actuality assign a label to an image? Also app seems to only accept jpg type, when selecting png it return white blank image...

![Untitled](https://user-images.githubusercontent.com/35932738/65314193-7d005400-db9e-11e9-85c6-a604ea33ac65.png)

**Comment by LKneringer** [comment]
You can assign the label, or object class as we call it, by pressing Left or Right on the Arrow Keys, or pressing the respective number on the keyboard.

Pardon the exception. I will submit a fix shortly. Meanwhile you can change the line
`return ColorTranslator.FromHtml(Colors[index]);`
to
`return ColorTranslator.FromHtml(Colors[index % Colors.Length]);`

Hope this helps.

We will look into the JPG/PNG issue.
